name: Database Insert and Release

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sqlite-utils
        run: |
          pip install sqlite-utils

      - name: Create reference.db and insert data
        run: |
          echo "Inserting data into reference.db"
          for file in reference/*.csv; do
            tablename=$(basename "$file" .csv)
            echo "Inserting $file into table $tablename"
            sqlite-utils insert reference.db "$tablename" "$file" --csv
          done
        shell: bash
      
      - name: Set version
        run: |
          version=$(date -u +"%Y-%m-%d")
          echo "version=${version}" >> $GITHUB_ENV
        shell: bash

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub provided token
        run: |
          version=$(cat $GITHUB_ENV | grep version | cut -d '=' -f 2)
          echo "Creating release for version ${version}"
          gh release create "$version" reference.db resource.db --title "Release $version" --notes "Automated release for $version"
        shell: bash

      - name: Upload release artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: reference.db
          asset_name: reference.db
          asset_content_type: application/x-sqlite3

      - name: Upload resource.db
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: resource.db
          asset_name: resource.db
          asset_content_type: application/x-sqlite3
